In [1]:
import numpy as np


In [2]:
Rows = int(input("Give the number of rows:"))  


Give the number of rows:2


In [13]:

Columns = int(input("Give the number of columns:"))  
  


Give the number of columns:2


In [14]:
print("Please write the elements of the matrix in a single line and separated by a space: ")  
elements = list(map(int, input().split()))   


Please write the elements of the matrix in a single line and separated by a space: 
2 4 5 6


In [16]:
matrixx = np.array(elements).reshape(Rows, Columns)  
print(matrixx)   


[[2 4]
 [5 6]]


In [17]:
Rows = int(input("Give the number of rows:"))
Columns = int(input("Give the number of columns:"))  

Give the number of rows:2
Give the number of columns:2


In [18]:
print("Please write the elements of the matrix in a single line and separated by a space: ")  
elements = list(map(int, input().split()))   

Please write the elements of the matrix in a single line and separated by a space: 
4 3 2 9


In [19]:
matrixx2 = np.array(elements).reshape(Rows, Columns)  
print(matrixx2) 

[[4 3]
 [2 9]]


In [21]:
#dot product
d=np.dot(matrixx,matrixx2)
print(d)

[[16 42]
 [32 69]]


In [26]:
#transpose
t = matrixx.transpose()
t2 = matrixx2.transpose()
print("transpose of first matrix\n",t)
print("transpose of second matrix\n",t2)

transpose of first matrix
 [[2 5]
 [4 6]]
transpose of second matrix
 [[4 2]
 [3 9]]


In [27]:
#trace
print("original matrix\n",matrixx)
tr = np.trace(matrixx)
print("Trace of matrix\n",tr)

original matrix
 [[2 4]
 [5 6]]
Trace of matrix
 8


In [28]:
#Rank
rank = np.linalg.matrix_rank(matrixx)
print("original matrix\n",matrixx)
print("Rank of matrix\n",rank)

original matrix
 [[2 4]
 [5 6]]
Rank of matrix
 2


In [29]:
#determinant
det= np.linalg.det(matrixx)
print("original matrix\n",matrixx)
print("Determinant of matrix\n",det)

original matrix
 [[2 4]
 [5 6]]
Determinant of matrix
 -7.999999999999998


In [32]:
#inverse
inv=np.linalg.inv(matrixx)
print("original matrix\n",matrixx)
print("Inverse of matrix\n",inv)

original matrix
 [[2 4]
 [5 6]]
Inverse of matrix
 [[-0.75   0.5  ]
 [ 0.625 -0.25 ]]


In [36]:
#eigen values and eigen vectors
w, v = np.linalg.eig(matrixx)
print("original matrix\n",matrixx)
print("eigen values of the matrix\n",w)
print("eigen vector of the matrix\n",v)

original matrix
 [[2 4]
 [5 6]]
eigen values of the matrix
 [-0.89897949  8.89897949]
eigen vector of the matrix
 [[-0.8097086  -0.50158596]
 [ 0.58683216 -0.86510781]]
